### ISSUE TITLE
Training time?

### ISSUE THREAD

**Issue by mstribitaka** [pclucas14/pixel-cnn#1]
Hey there, 

Been trying out your code and just wondering what GPU card you're using and how long it takes? I'm using a GTX 1080 and it's taking around 1 hour for 1 epoch. Does that sound reasonable to you? 

We had to reduce the batch size to 64 otherwise it ran out of memory. 

Thanks!

**Comment by pclucas14** [comment]
Hi, 

thanks for your question. I'm running on a TitanX and it takes 50 minutes per epoch. There's currently a [bug](https://github.com/pytorch/pytorch/issues/3883)  with DataParallel which prevents multi-gpu training, but once that's solved training time should go down!

Update : @mstribitaka I had a small memory overlap in the testing loop, you should now be able to double the batch size

**Comment by pclucas14** [comment]
I'm gonna close this issue, as training time is reasonable on multi gpu. I tested on pytorch 0.2 and speed seems proportional to the amount of gpus available.
