### ISSUE TITLE
Loading pretrained model 

### ISSUE THREAD

**Issue by arunesh-mittal** [pclucas14/pixel-cnn#14]
Hi Lucas!

Thanks so much for sharing this implementation! :) 

Ran into a snag while loading the pre-trained model. Seems like the pretrained models were saved using `DataParallel` so naively loading the model throws error. Just calling `model = torch.nn.DataParallel(model)` and then calling `load_part_of_model` fixes the issue. 

It's a minor thing but just in case others run into the same issue.

Best,

**Comment by pclucas14** [comment]
Hi, 

thanks for flagging this! I'll fix this soonish. I'll leave the issue open until then 

-Lucas
