### ISSUE TITLE
Pretrained model request after higher number of epochs, possibly end of training

### ISSUE THREAD

**Issue by rsbandhu** [pclucas14/pixel-cnn#15]
Hi Lucas, thanks for posting some of the pretrained models.
Based on your code, it appears that the pretrained models are after 789, 889 epochs. Is that correct?
In the code, it appears much longer than that. Is it possible to share the trained model after higher epoch counts, around 5000?

Also, is it possible to use this pre-trained model for another dataset such as SVHN or do I need to train them from scratch?

Thanks for your response

**Comment by pclucas14** [comment]
Hi, 

Unfortunately I don't have the pretrained models available anymore. 
You will most likely have to retrain a new model for SVHN, although if the input is the same size as CIFAR10, you can always start SVHN training from the pretrained model.

-Lucas
