### ISSUE TITLE
Train for my own dataset

### ISSUE THREAD

**Issue by NeroArcher** [pclucas14/pixel-cnn#18]
Thank you for your advice last time, I can run the trainning process properly after that. My next goal is to train it with my own dataset(probably hundreds of images) instead of Mnist or Cifar. I have read something about the dataloader part but I am still a little confused about where and how I should do the adjusting in the code. May I get any more advice from you?

**Comment by pclucas14** [comment]
It's hard to say with this little information. Probably best to build your [own Pytorch Dataset ](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html), then change places in the code where the data size is hardcoded. After that hopefully it works.

**Comment by NeroArcher** [comment]
> It's hard to say with this little information. Probably best to build your [own Pytorch Dataset ](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html), then change places in the code where the data size is hardcoded. After that hopefully it works.

Thank you! I will learn from there!
