### ISSUE TITLE
Pre-trained Model Request

### ISSUE THREAD

**Issue by lxuniverse** [pclucas14/pixel-cnn#3]
Hi:

Thanks for your amazing job.

Is it possible that you give the access of your pre-trained model?

Thanks!

**Comment by pclucas14** [comment]
Hi, 

sorry for the late reply, I just saw this. I will try to upload a few, just need to figure out what is the best way to proceed. 

-Lucas

**Comment by pclucas14** [comment]
Let me know if this works for you 
https://mega.nz/#F!W7IhST7R!PV7Pbet8Q07GxVLGnmQrZg

**Comment by mmazeika** [comment]
When I use load_state_dict instead of load_part_of_model, I get the error
> KeyError: 'unexpected key "module.down_layers.0.u_stream.0.conv_input.conv.bias" in state_dict'

load_part_of_model doesn't load anything for me. Was the model code changed at some point?

**Comment by mmazeika** [comment]
Problem solved. There needed to be a DataParallel wrapper around the model in order to load the parameters.

**Comment by rsbandhu** [comment]
Hi Lucas, thanks for posting some of the pretrained models. 
Based on your code, it appears that the pretrained models are after 789, 889 epochs. Is that correct?
In the code, it appears much longer than that. Is it possible to share the trained model after higher epoch counts, around 5000?

Also, is it possible to use this pre-trained model for another dataset such as SVHN or do I need to train them from scratch?

Thanks for your response
