### ISSUE TITLE
License

### ISSUE THREAD

**Issue by aldro61** [pclucas14/pixel-cnn#5]
Thanks for this great implementation of PixelCNN. Could you please add a license to your repo? This will allow others to reuse your code "properly".

You can use this [license picker](https://choosealicense.com).

Thanks in advance!

**Comment by vsub21** [comment]
Seconded! Please add a license to your repo, it would be much appreciated. :)

**Comment by pclucas14** [comment]
Done!

**Comment by pclucas14** [comment]
Sorry for the late reply on this!
